# Generated by Django 3.2 on 2024-01-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_pant_saree_tshirt'),
    ]

    operations = [
    ]
